config/routes.rb
Rails.application.routes.draw do

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
resources :users
resources :sessions

  root 'movies#home'

    get 'movies/kannada' => 'movies#kannada'
    get 'movies/tamil' => 'movies#tamil'
    get 'movies/telagu' => 'movies#telagu'
    get 'movies/malyalam' => 'movies#malyalam'
    get 'movies/hindi' => 'movies#hindi'
    get 'movies/english' => 'movies#english'
    get 'movies/others' => 'movies#others'

    resources :movies

end

app/models/movie.rb
class Movie < ActiveRecord::Base

   LANGUAGE = ['kannada', 'tamil', 'telagu', 'hindi', 'malyalam', 'english', 'others']
   RATING = ['excelent', 'good', 'poor', 'worst']

   belongs_to :user

   validates_presence_of :name
   validates_presence_of :language
   validates_presence_of :rating



def self.search(search, language)
  if search.present?
   @movies = Movie.where("LOWER(name) = LOWER('#{search}') and LOWER(language) = LOWER('#{language}') ")
  else
    @movies = Movie.where("language = ? ", language)
  end
  return @movies
end


end

app/models/user.rb
class User < ActiveRecord::Base
  
  attr_accessor :password
  before_save :encrypt_password


  has_many :movies
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(username, password)
    user = find_by_username(username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_login
    unless session[:user_id]
     flash[:error] = "You must be logged in to access this section"
     redirect_to root_path 
   end
 end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

before_filter :require_login, except: [:home] 

  def new
    @movie = Movie.new
    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  def create
    @movie = Movie.new(movies_params)
    @movie.owner_id = current_user.id
   if @movie.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def home
  end
  
  def index
    @movies = Movie.all
  end

  def show  
  end

  def kannada
    @movies = Movie.search(params[:search], 'kannada')
  end

  def hindi
    @movies = Movie.search(params[:search], 'hindi')
  end

  def tamil
    @movies = Movie.search(params[:search], 'tamil')
  end

  def telagu
    @movies = Movie.search(params[:search], 'telagu')
  end

  def malyalam
    @movies = Movie.search(params[:search], 'malyalam')
  end

  def english
    @movies = Movie.search(params[:search], 'english')
  end

  def others
    @movies = Movie.search(params[:search], 'others')
  end

  private

  def movies_params
    params.require(:movie).permit(:name, :language, :owner_id, :rating)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
end

def create
  @user = User.authenticate(params[:username], params[:password])
  if @user
    session[:user_id] = @user.id
    redirect_to root_url, :notice => "Logged in!"
  else
    flash.now.alert = "Invalid email or password"
    render "new"
  end
end

def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Logged out!"
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  @user = User.new
end

def create
  @user = User.new(user_params)
  if @user.save
    redirect_to root_url, :notice => "Signed up!"
  else
    render "new"
  end
end

private

def user_params
  params.require(:user).permit(:username, :email, :password, :password_confirmation)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_overlays.html.erb
<div id="div_modal_generic" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body-main"></div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div id="div_modal_message" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <p>One fine body&hellip;</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MoviesInfo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<center>
<%= form_for :movie, url: movies_path do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@movie.errors.count, "error") %> prohibited
        this movie from being saved:
      </h2>
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :Language %>
    <%= f.select :language, Movie::LANGUAGE %>
  </p>
  <p>
    <%= f.label :Quality_Rating %>
    <%= f.select :rating, Movie::RATING %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %> 
</center>

app/views/movies/_list_movies.html.erb
<div class="modal-content">
<center>
    <%= form_tag movies_kannada_path, :method => 'get' do %>
            <p>
              <%= text_field_tag :search, params[:search] %>
              <%= submit_tag "Search", :name => nil %>
            </p>
    <% end %>
</center>
<div class="container">
<h4 class="match-heading-link"></h4>
<div class="row">
   <div class="col-sm-12">
        <h4 class="col-sm-3 color-of-heading">Name</h4>
        <h4 class="col-sm-3 color-of-heading">Owner</h4>
        <h4 class="col-sm-3 color-of-heading">rating </h4>
   </div>
<br>
<div class="journal-entry-devider"></div>

<% @movies.each do |m| %>
<% user = User.find(m.owner_id)%>
<div class="message-box">
    <div class="col-sm-12">
        <div class="col-sm-3"><%= m.name %></div>
        <div class="col-sm-3 winner-name message-box-high"><%= user.username if m.owner_id? %></div>
        <div class="col-sm-2"><%= m.rating %> </div>
        <div class="col-sm-2"></div>
        <div class="journal-entry-devider"></div>
    </div>
</div>
<% end %>
</div>
</div>
</div>

app/views/movies/create.html.erb
<%= form_for :movie, url: movies_path do |f| %>
 
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@movie.errors.count, "error") %> prohibited
        this movie from being saved:
      </h2>
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :language %><br>
    <%= f.text_area :language %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', movies_path %>

app/views/movies/english.html.erb
<div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="logo text-center">
                            <h1>English</h1>
                        </div>
                    </div>
                </div>
            </div>
<%= render :partial => "list_movies" %>

app/views/movies/hindhi.html.erb
<div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="logo text-center">
                            <h1>Hindhi</h1>
                        </div>
                    </div>
                </div>
            </div>
<%= render :partial => "list_movies" %>

app/views/movies/hindi.html.erb
<div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="logo text-center">
                            <h1>hindi</h1>
                        </div>
                    </div>
                </div>
            </div>
<%= render :partial => "list_movies" %>

app/views/movies/home.html.erb
<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <div id="user_nav">
            <% if current_user %>
                Logged in as <%= current_user.username %>.
                <%= link_to "Log out", log_out_path %>
            <% else %>
                <%= link_to "Sign up", sign_up_path %> or
                <%= link_to "log in", log_in_path %>
            <% end %>
        </div>

        <title>Movies</title>
        <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function(){
                $("#myModal").modal('show');
            });
        </script>

        <!-- Template js -->

        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>
    
    <body>
        
        <%= render :partial=>"/layouts/overlays" -%>
        <!-- Start Logo Section -->
        <section id="logo-section" class="text-center">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="logo text-center">
                            <h1>Movies</h1>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- End Logo Section -->
        <% flash.each do |name, msg| -%>
            <%= content_tag :div, msg, class: name %>
        <% end -%>
        <!-- Start Main Body Section -->
        <div class="mainbody-section text-center">
            <div class="container">
                <div class="row">
                    
                    <div class="col-md-3">
                        
                        <div class="menu-item blue">
                            <%= link_to 'Kannada', movies_kannada_path %>
                        </div>
                        
                        <div class="menu-item green">
                            <%= link_to 'Tamil', movies_tamil_path %>
                        </div>
                        
                        <div class="menu-item light-red">
                            <%= link_to 'Telagu', movies_telagu_path %>
                        </div>
                        
                    </div>
                    
                    <div class="col-md-6">
                        
                        <!-- Start Carousel Section -->
                        <div class="home-slider">
                            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" style="padding-bottom: 30px;">
                                <!-- Indicators -->
                                <ol class="carousel-indicators">
                                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                                </ol>

                                <!-- Wrapper for slides -->
                                <div class="carousel-inner">
                                    <div class="item active">
                                        <img src="assets/about-03.jpg" class="img-responsive" alt="">
                                    </div>
                                    <div class="item">
                                        <img src="assets/about-02.jpg" class="img-responsive" alt="">
                                    </div>
                                    <div class="item">
                                        <img src="assets/about-01.jpg" class="img-responsive" alt="">
                                    </div>

                                </div>

                            </div>
                        </div>
                        <!-- Start Carousel Section -->
                        <div class="row">
                            <div class="col-md-12">
                                <div class="menu-item color responsive">
                                    <%= link_to 'English', movies_english_path %>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-md-12">
                                <div class="menu-item color responsive">
                                        <i class="fa fa-area-chart"></i>
                                    <%= link_to 'Add movie', new_movie_path, remote: true %>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-md-3">
                        
                        <div class="menu-item light-red">
                            <%= link_to 'Hindi', movies_hindi_path %>
                        </div>
                        
                        <div class="menu-item color">
                            <%= link_to 'Malyalam', movies_malyalam_path %>
                        </div>
                        
                        <div class="menu-item blue">
                            <%= link_to 'Others', movies_others_path %>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
        <!-- End Main Body Section -->
        
        <!-- Start Copyright Section -->
        <div class="copyright text-center">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div>Developed <a href="https://www.facebook.com/akshaysimha" target="_blank">Akshay Simha</a> for <a href="http://qwinixtech.com">Qwinix</a></div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Copyright Section -->
        
    </body>
    
</html>

app/views/movies/index.html.erb
<%= render :partial => "list_movies" %>

app/views/movies/kannada.html.erb
<div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="logo text-center">
                            <h1>Kannada</h1>
          
                        </div>
                    </div>
                </div>
                



            </div>
<%= render :partial => "list_movies" %>

app/views/movies/malyalam.html.erb
<div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="logo text-center">
                            <h1>Malyalam</h1>
                        </div>
                    </div>
                </div>
            </div>
<%= render :partial => "list_movies" %>

app/views/movies/new.html.erb
<%= form_for :movie, url: movies_path do |f| %>
 
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@movie.errors.count, "error") %> prohibited
        this movie from being saved:
      </h2>
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.select :language, Movie::LANGUAGE %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', movies_path %>

app/views/movies/new.js.erb
heading = "Add Movie";
bodyContent = "<%= escape_javascript(render(:partial=>"form")) %>";
showModal(heading, bodyContent);

app/views/movies/others.html.erb
<div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="logo text-center">
                            <h1>Others</h1>
                        </div>
                    </div>
                </div>
            </div>
<%= render :partial => "list_movies" %>

app/views/movies/tamil.html.erb
<div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="logo text-center">
                            <h1>Tamil</h1>
                        </div>
                    </div>
                </div>
            </div>
<%= render :partial => "list_movies" %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :username %>:<br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %>:<br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %>:<br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>:<br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>